Solution
mate-academy/js_task-detect-pangram pull request #127
Opened 2020-05-21 15:56 UTC by liliya-dev

2020-05-23 07:26 UTC, hryshko-denys approved these changes
Все отлічно.
було б непогано замість 26 написати alpha.length, додає більше логіки

2020-05-25 08:37 UTC, danheim requested changes

2020-05-25 08:37 UTC, danheim commented on src/detect-pangram.js
> +  let count = 0;
```suggestion
  let counter = 0;
```

2020-05-25 08:37 UTC, danheim commented on src/detect-pangram.js
> +  const alpha = 'abcdefghijklmnopqrstuvwxyz';
не сокращай названия

2020-05-25 08:37 UTC, danheim commented on src/detect-pangram.js
> +  return count === 26;
alphabet.length

2020-05-25 09:59 UTC, danheim commented on src/detect-pangram.js
> +  return counter === 26;
<img width="694" alt="Screenshot 2020-05-25 at 12 58 39" src="https://user-images.githubusercontent.com/36257947/82802421-89545380-9e87-11ea-8fd2-f2b868e18c83.png">

2020-05-25 16:01 UTC, danheim commented on src/detect-pangram.js
> +    if (phrase.toLowerCase().includes(alphabet[i])) {
приведи phrase к нижнему регистру до цикла

2020-05-25 16:01 UTC, danheim approved these changes

2023-03-15 11:01 UTC, closed without merging