Solution
mate-academy/js_task-detect-pangram pull request #136
Opened 2020-05-22 13:06 UTC by ogsevko

2020-05-22 13:56 UTC, solaryasha approved these changes

2020-05-22 13:56 UTC, solaryasha commented on src/detect-pangram.js
> +    return false;
Можеш записати це одним рядком
`return Object.keys(alphabet).length === numberOfLetters)`

2020-05-22 17:29 UTC, ogsevko commented on src/detect-pangram.js
> +    return false;
Туплю))

2020-05-25 08:46 UTC, danheim requested changes

2020-05-25 08:46 UTC, danheim commented on src/detect-pangram.js
> +  const numberOfLetters = 26;
```suggestion
  const alphabetLength = 26;
```

2020-05-25 08:46 UTC, danheim commented on src/detect-pangram.js
> +  const alphabet = {};
в этом задании можно обойтись без объектов

2020-05-25 10:02 UTC, danheim requested changes

2020-05-25 10:02 UTC, danheim commented on src/detect-pangram.js
> +    if (phrase.toLowerCase().indexOf(alphabet[i]) === -1) {
приведи к lowerCase до цикла
зачем приводить каждую итерацию если можно один раз?

2020-05-25 16:03 UTC, danheim approved these changes

2020-05-25 16:03 UTC, danheim commented on src/detect-pangram.js
> +  const sentence = phrase.toLowerCase();
```suggestion
  const phraseLowerCase = phrase.toLowerCase();
```

2023-12-26 21:45 UTC, closed without merging